Cypress.on('uncaught:exception', (err, runnable) => {
  return false
}
)
let rowsLength
describe('Scope tool Testing (Validation)', () => {
  before(()=>{

      cy.task('readXlsx', { file: 'Cypress/fixtures/validation.xlsx', sheet: "Sheet1" }).then((rows) => {
        rowsLength = rows.length;
        cy.writeFile("Cypress/fixtures/validation.json", { rows })
    })
  
    })
  it("1.Login to scoping tool", () => {
    cy.visit('https://cybersecurity.att.com/order/scopes/login/')
    cy.fixture('validation').then((user) => {
      cy.get('#id_username').type(user.rows[0].username)
      cy.get('#id_password').type(user.rows[0].password)
      cy.wait(1000)
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(1) div.col-md-6.offset-md-3 div.vstack.gap-3 div.bg-light:nth-child(1) form.my-4:nth-child(2) div.d-grid.gap-2:nth-child(4) > button.btn.btn-primary:nth-child(1)').click()
      Cypress.Cookies.preserveOnce()
    })
  })
      it('checking for the elements in Review page',function(){
        cy.visit('https://cybersecurity.att.com/order/scopes/login/')
        cy.fixture('validation').then((user) => {
          cy.get('#id_username').type(user.rows[0].username)
          cy.get('#id_password').type(user.rows[0].password)
          cy.wait(1000)
          cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(1) div.col-md-6.offset-md-3 div.vstack.gap-3 div.bg-light:nth-child(1) form.my-4:nth-child(2) div.d-grid.gap-2:nth-child(4) > button.btn.btn-primary:nth-child(1)').click()
          Cypress.Cookies.preserveOnce()
          cy.wait(1000)
      //To validate ' open review ' eye icon
      //cy.xpath('//*[@id="dataTable_wrapper"]/div/div[5]/div[3]/div[2]/div/table/tbody/tr[1]/td/div/button[2]').invoke('removeAttr', 'data-uuid', '6cd61e5f-f277-4a53-a227-c7223c22e60a').click()
      cy.visit('https://cybersecurity.att.com/order/scopes/scope/6cd61e5f-f277-4a53-a227-c7223c22e60a/review/')
   
     //Checking for the elements in validation page
    cy.contains('AT&T Cybersecurity: USM Anywhere')
      //cy.contains('Sent To Customer')
      cy.contains('Overview')
      //cy.contains('General Actions')
      cy.contains('Generate Results')
      cy.contains('Email Customer')
      cy.contains('Download Spreadsheet')
      cy.contains('View Audit')
      cy.contains('State Actions')
      cy.contains('Review with Limitations')
      cy.contains('Complete Review')
      cy.contains('Skip Salesforce and Complete Review')
      cy.contains('Reject')
      cy.contains('Move to Closed Won')
      cy.contains('Required Compliance')
      cy.contains('Scoping General Notes & Considerations')
      cy.contains('AWS Environment')
      cy.contains('Native AWS logs')
      cy.contains('Azure Environment')
      cy.contains('GCP Environment')
      cy.contains('Logs To Collect')
      cy.contains('AlienApps')
      cy.contains('On-Premise Locations')
      cy.contains('Location types with direct internet access')
      cy.contains('On-Prem: Network Data Sources')
      cy.contains('On-Prem: Server/Endpoint Data Sources')
      cy.contains('Save')
      cy.wait(2000)
      //To validate 'Generate Results' button
      //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2:nth-child(2) div.card:nth-child(1) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.generateResults.btn-block:nth-child(1)').click()
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2 div.card:nth-child(1) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.generateResults.btn-block:nth-child(1)').click()
      cy.wait(1000)
      //To validate 'Email Customer' button
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2 div.card:nth-child(1) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.resendEmailButton.btn-block:nth-child(2)').click()
      cy.wait(1000)
      //To validate 'Email Customer' button with invalid data
      cy.get('#id_subject').clear()
      cy.wait(1000)
      cy.get('#sendEmailToCustomer').click()
      cy.get('#newResendCustomerEmailModal > .modal-dialog > .modal-content > .modal-body > .alert').scrollIntoView()
      cy.wait(3000)
      cy.contains('You must send a subject').should('be.visible')
      cy.scrollTo('top')
      cy.wait(1000)
      //To validate 'Email Customer' button with valid data
      cy.get('#id_subject').type(user.rows[0].subject)
      cy.wait(1000)
      cy.get('#sendEmailToCustomer').click()
      cy.wait(1000)
      //To validate 'close' icon
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2 div.card:nth-child(1) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.resendEmailButton.btn-block:nth-child(2)').click({ force: true })
      cy.wait(1000)
      //cy.get('body.modal-open:nth-child(2) div.container:nth-child(2) main.my-4 div.modal.fade.show:nth-child(5) div.modal-dialog div.modal-content div.modal-header > button.btn-close').click()
      cy.wait(1000)
      //To validate 'close' button
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2 div.card:nth-child(1) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.resendEmailButton.btn-block:nth-child(2)').click({ force: true })
      cy.wait(1000)
      cy.get('body.modal-open:nth-child(2) div.container:nth-child(2) main.my-4 div.modal.fade.show:nth-child(5) div.modal-dialog div.modal-content div.modal-footer > button.btn.btn-secondary:nth-child(1)').click()
      cy.wait(2000)
      //To Check if the excel file is downloaded when the user clicks the 'Download Spreadsheet' button
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2 div.card:nth-child(1) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.downloadSpreadsheet.btn-block:nth-child(3)').click()
      cy.wait(2000)
        })
      })
        it("To Check if page is redirect to ' view audit' form page when user clicking on ' view audit' button",function(){
          cy.visit('https://cybersecurity.att.com/order/scopes/login/')
          cy.fixture('validation').then((user) => {
            cy.get('#id_username').type(user.rows[0].username)
            cy.get('#id_password').type(user.rows[0].password)
            cy.wait(1000)
            cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(1) div.col-md-6.offset-md-3 div.vstack.gap-3 div.bg-light:nth-child(1) form.my-4:nth-child(2) div.d-grid.gap-2:nth-child(4) > button.btn.btn-primary:nth-child(1)').click()
            Cypress.Cookies.preserveOnce()
            cy.wait(1000)
        //To validate ' open review ' eye icon
        //cy.xpath('//*[@id="dataTable_wrapper"]/div/div[5]/div[3]/div[2]/div/table/tbody/tr[1]/td/div/button[2]').invoke('removeAttr', 'data-uuid', '6cd61e5f-f277-4a53-a227-c7223c22e60a').click()
        cy.visit('https://cybersecurity.att.com/order/scopes/scope/6cd61e5f-f277-4a53-a227-c7223c22e60a/review/')
      //To Check if page is redirect to ' view audit' form page when user clicking on ' view audit' button
      cy.xpath('//*[@id="mainContainer"]/main/div[3]/div[1]/div[1]/div[1]/div[2]/div/a').invoke('removeAttr', 'target').click()
      cy.wait(2000)
      //To validate 'History' tab
      cy.scrollTo('bottom')
      cy.wait(500)
      cy.get('#show_diff').click()
      //To validate 'Diff Compare' tab
      cy.get('#show_diff').click()
      cy.wait(500)
      //To validate ' Email Recipients by State' tab
      cy.get('#show_emails').click()
      cy.contains('Created')
      cy.contains('Customer Submitted')
      cy.contains('Sent To Customer')
      cy.contains('MSSP Review Request')
      cy.contains('MSSP Review Denied')
      cy.contains('Sent For Review')
      cy.contains('Review with Limitations')
      cy.contains('Limitation Response')
      cy.contains('Rejected')
      cy.contains('Rejection Response')
      cy.contains('Review Complete')
      cy.contains('Review Denied')
      cy.contains('Invalid')
      cy.contains('Invalid Response')
      cy.contains('Closed')
      cy.contains('Archived')
      cy.contains('Not Interested')
      cy.contains('Closed Won')
      cy.wait(1000)
      //To validate 'Show comments' tab
      cy.get('#show_comments').click()
      cy.wait(1000)
        })
      })
      /* cy.visit('https://cybersecurity.att.com/order/scopes/scope/ad779a10-770d-42c1-a368-9bbc87dc5194/validate/')
 
      //To validate 'Validate with Limitations' button
      cy.wait(1000)
      cy.scrollTo(0,500)
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2 div.card:nth-child(2) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.limitationScope.btn-block:nth-child(1)').click()
 
      cy.wait(1000)
      cy.scrollTo('top')
      cy.contains('Validate the scope with Limitations')
      //cy.contains('Specifiy limitations for the concern of the scope.')
      cy.get('#limitationDetails').type(user.rows[0].limitationDetail)
      cy.wait(1000)
      //cy.get('#sendLimitationRequest').click()
      cy.get('body.modal-open:nth-child(2) div.container:nth-child(2) main.my-4 div.modal.fade.show:nth-child(7) div.modal-dialog div.modal-content div.modal-header > button.btn-close').click()
      cy.scrollTo('top')
      //cy.contains('Failure!')
      cy.wait(1000)
      //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2:nth-child(2) div.card:nth-child(2) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.limitationScope.btn-block:nth-child(1)').click()
 
      //cy.get('#limitationDetails').type(3)
      //cy.get('#sendLimitationRequest').click()
 
 
 
      //cy.visit('https://cybersecurity.att.com/order/scopes/scope/44158c40-9377-4ff4-9c42-74c67a8d196f/validate/')
      //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2:nth-child(2) div.card:nth-child(2) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.limitationScope.btn-block:nth-child(1)').click({force: true})
       //cy.get('#limitationDetails').type(3)
       //cy.get('#sendLimitationRequest').click()
       //cy.wait(2000)
      // cy.contains('Response Required')
      // cy.contains('Respond')
      // cy.contains('Valid with Limitations')
      //cy.get('body.modal-open:nth-child(2) div.container:nth-child(2) main.my-4 div.modal.fade.show:nth-child(7) div.modal-dialog div.modal-content div.modal-header > button.btn-close').click()
      cy.wait(1000)
       cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) > button.commentRespond.btn.btn-dark').click()
       //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) > button.commentRespond.btn.btn-dark')cy.wait(2000)
       cy.contains('Respond and Approve')
       cy.contains('Respond and Decline')
       cy.contains('Send Response')
       //Negative and positive scenarios of Send Response
       cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) div.sendActionBar > button.sendResponse.btn.btn-dark:nth-child(3)').click()
       cy.scrollTo('top')
       cy.wait(1000)
       cy.scrollTo('top')
       //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body:nth-child(4) form:nth-child(1) > textarea.form-control.commentText').type('Test Message')
       cy.wait(1000)
       cy.scrollTo('top')
       cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) div.sendActionBar > button.sendResponse.btn.btn-dark:nth-child(3)').click({force: true})
       cy.wait(2000)
 
 
       cy.visit('https://cybersecurity.att.com/order/scopes/scope/96556562-a193-4d7d-b2fe-10f37550ba25/validate/')
       cy.wait(2000)
       
 
        //Negative and positive scenarios of Respond and approve
 
        //valid with limitation button
        cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2 div.card:nth-child(2) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.limitationScope.btn-block:nth-child(1)').click({force: true})
        cy.wait(1000)
        cy.get('#limitationDetails').type(user.rows[0].limitationDetail)
        cy.wait(1000)
        cy.get('#sendLimitationRequest').click()
        cy.wait(2000)
        cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) > button.commentRespond.btn.btn-dark').click()
        cy.wait(2000)
        cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) div.sendActionBar > button.sendResponse.btn.btn-primary:nth-child(1)').click()
        cy.scrollTo('top')
        cy.wait(1000)
        cy.scrollTo('top')
        cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body:nth-child(4) form:nth-child(1) > textarea.form-control.commentText').type(user.rows[0].sendresponse)
        cy.wait(1000)
        cy.scrollTo('top')
        cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) div.sendActionBar > button.sendResponse.btn.btn-primary:nth-child(1)').click()
        cy.wait(2000)
 
cy.pause()
        cy.visit('https://cybersecurity.att.com/order/scopes/scope/96556562-a193-4d7d-b2fe-10f37550ba25/validate/')
        cy.wait(2000)
 
         //Negative and positive scenarios of Respond and decline
 
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2 div.card:nth-child(2) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.limitationScope.btn-block:nth-child(1)').click()
         cy.wait(2000)
         cy.get('#limitationDetails').type(user.rows[0].limitationDetail)
         cy.wait(2000)
         cy.get('#sendLimitationRequest').click()
         cy.wait(2000)
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) > button.commentRespond.btn.btn-dark').click()
         cy.wait(2000)
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) div.sendActionBar > button.sendResponse.btn.btn-danger:nth-child(2)').click()
         cy.wait(2000)
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body:nth-child(4) form:nth-child(1) > textarea.form-control.commentText').type(user.rows[0].sendresponsemessage)
         cy.wait(1000)
         cy.scrollTo('top')
         cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 div.card.mb-4.text-dark.bg-light:nth-child(3) div.card-body.text-end:nth-child(5) div.sendActionBar > button.sendResponse.btn.btn-danger:nth-child(2)').click()
         cy.wait(2000)*/

        it('validating the Skip Salesforce and Validate, Reject, Moved to close won, Move to Archeive and overview form ', function(){
          cy.visit('https://cybersecurity.att.com/order/scopes/login/')
          cy.fixture('validation').then((user) => {
            cy.get('#id_username').type(user.rows[0].username)
            cy.get('#id_password').type(user.rows[0].password)
            cy.wait(1000)
            cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(1) div.col-md-6.offset-md-3 div.vstack.gap-3 div.bg-light:nth-child(1) form.my-4:nth-child(2) div.d-grid.gap-2:nth-child(4) > button.btn.btn-primary:nth-child(1)').click()
            Cypress.Cookies.preserveOnce()
            cy.wait(1000)
        //To validate ' open review ' eye icon
        //cy.xpath('//*[@id="dataTable_wrapper"]/div/div[5]/div[3]/div[2]/div/table/tbody/tr[1]/td/div/button[2]').invoke('removeAttr', 'data-uuid', '6cd61e5f-f277-4a53-a227-c7223c22e60a').click()
        cy.visit('https://cybersecurity.att.com/order/scopes/scope/6cd61e5f-f277-4a53-a227-c7223c22e60a/review/')

          //To validate 'Skip Salesforce and Validate' button
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2 div.card:nth-child(2) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.skipSFDCScope.btn-block:nth-child(3)').click()
      cy.wait(3000)

      //To validate 'Move to Closed Won' button
      cy.xpath('//*[@id="mainContainer"]/main/div[3]/div[1]/div[1]/div[2]/div[2]/div/button[5]').click({ force: true })
      //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2:nth-child(2) div.card:nth-child(2) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.closedWonScope.btn-block:nth-child(4)')
      cy.wait(1000)

      //To validate 'Move to Archive' button
      cy.xpath('//*[@id="mainContainer"]/main/div[3]/div[1]/div[1]/div[2]/div[2]/div/button[6]').click()
      cy.wait(1000)

      //validating validate button

      //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-4 div.d-grid.gap-2:nth-child(2) div.card:nth-child(2) div.card-body div.d-grid.gap-2 > button.btn.btn-primary.validateScope.btn-block:nth-child(2)').click()
      //cy.wait(2000)

      //Save validation form
      //cy.get('#saveForm').click()
      cy.wait(2000)

      cy.wait(1000)
      cy.contains("Does the customer's company policy allow logs to be off premise and hosted on AWS?:")
      cy.contains('What goal is the customer trying to achieve with USM Anywhere?:')
      cy.contains('What Subdomain name does customer require?')
      cy.contains('Does the customer have geographic requirements?')
      cy.contains('Does the customer have an existing security teams?')
      cy.contains('Do all your sites have interconnectivity?')
      cy.contains('How many public facing web servers?')
      cy.contains('If you have public facing web servers, how many external users would you expect?')
      cy.contains('PCI')
      cy.contains('HIPAA')
      cy.contains('ISO')
      cy.contains('FedRAMP')
      cy.contains('Scoping General Notes & Considerations')
      cy.wait(2000)
      cy.contains('General Notes & Considerations')
      cy.contains('AWS Environment')
      cy.contains('Accounts - How many accounts do you have?')
      cy.contains('EC2 Windows/Linux - How many instances?')
      cy.contains('S3 Buckets - How many S3 Buckets to Monitor total?')
      cy.contains('Native AWS logs')
      cy.contains('CloudTrail')
      cy.contains('CloudWatch')
      cy.contains('VPC Flow Logs (Very Noisy)')
      cy.contains('Azure Environment')
      cy.contains('GCP Environment')
      cy.contains('Logs To Collect')
      cy.contains('Firewall Logs')
      cy.contains('VPC Flow Logs')
      cy.contains('AlienApps')
      cy.wait(2000)
      cy.contains('O365 - How many Office365 users?')
      cy.contains('G-Suite - How many Gsuite users?')
      cy.contains('Okta - How many Okta users?')
      cy.contains('Zscaler Nanolog - How many users?')
      cy.contains('Cisco Umbrella - How many users?')
      cy.contains('Cisco Amp - How many endpoints?')
      cy.contains('McAfee ePO - How many McAfee ePO endpoints?')
      cy.contains('Sophos - How many Sophos endpoints and/or devices?')
      cy.contains('Carbon Black - How many Carbon Black endpoints?')
      cy.contains('Crowdstrike - How many Crowdstrike endpoints?')
      cy.contains('SentinelOne - How many SentinelOne endpoints?')
      cy.contains('CASB Solution - How many users?')
      cy.contains('Vulnerability Manager/Scanner (DDI/Qualys) - How many endpoints?')
      cy.contains('On-Premise Locations')
      cy.wait(2000)
      cy.contains('Location types with direct internet access')
      cy.contains('Number of locations (sensor deployment) - Datacenter')
      cy.contains('Number of locations (sensor deployment) - HQ/Main')
      cy.contains('Number of locations (sensor deployment) - Branch')
      cy.contains('On-Prem: Network Data Sources')
      cy.contains('On-Prem: Server/Endpoint Data Sources')

      //Dropdowns in validation Page

      //Does the customer have geographic requirements?

      cy.scrollTo('top')
      cy.wait(1000)
      cy.get('#id_0__0__3').select(1)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(2)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(3)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(4)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(5)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(6)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(7)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(8)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(9)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(10)
      cy.wait(1000)
      cy.get('#id_0__0__3').select(0)
      cy.wait(1000)
      //cy.get('#id_0__0__3').select(1)
      cy.wait(1000)
      //Does the customer have an existing security teams?
      cy.get('#id_0__0__4').select(1)
      cy.wait(1000)
      cy.get('#id_0__0__4').select(2)
      cy.wait(1000)
      cy.wait(5000)
      cy.get('#id_0__0__4').select(0)
      cy.wait(1000)
      //Do all your sites have interconnectivity?
      cy.get('#id_0__0__5').select(1)
      cy.wait(1000)
      cy.get('#id_0__0__5').select(2)
      cy.wait(1000)
      cy.get('#id_0__0__5').select(0)
      //PCI
      cy.wait(1000)
      cy.get('#id_0__1__0').select(1)
      cy.wait(1000)
      cy.get('#id_0__1__0').select(2)
      cy.wait(1000)
      cy.get('#id_0__1__0').select(0)
      //HIPAA
      cy.wait(1000)
      cy.get('#id_0__1__1').select(1)
      cy.wait(1000)
      cy.get('#id_0__1__1').select(2)
      cy.wait(1000)
      cy.get('#id_0__1__1').select(0)
      //ISO
      cy.wait(1000)
      cy.get('#id_0__1__2').select(1)
      cy.wait(1000)
      cy.get('#id_0__1__2').select(2)
      cy.wait(1000)
      cy.get('#id_0__1__2').select(0)
      //FedRAMP
      cy.wait(1000)
      cy.get('#id_0__1__3').select(1)
      cy.wait(1000)
      cy.get('#id_0__1__3').select(2)
      cy.wait(1000)
      cy.get('#id_0__1__3').select(0)

      //save button,back to top and logout button

     // cy.visit('https://cybersecurity.att.com/order/scopes/scope/96556562-a193-4d7d-b2fe-10f37550ba25/validate/')
      cy.wait(2000)
      cy.scrollTo('bottom')
      cy.wait(2000)
      cy.scrollTo('bottom')
      cy.wait(2000)
      cy.get('#saveForm').click()
      cy.wait(2000)
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 form.form-inline:nth-child(4) div.sticky-bottom.well.bg-light.p-4.border div.btn-group > button.btn.bg-info.bg-opacity-25.expandAll:nth-child(3)').click()
      cy.wait(1000)
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 form.form-inline:nth-child(4) div.sticky-bottom.well.bg-light.p-4.border div.btn-group button.btn.bg-info.bg-opacity-25.collapseAll:nth-child(2) > i.bi.bi-arrows-collapse').click()
      cy.wait(1000)
      cy.scrollTo('bottom')
      cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 form.form-inline:nth-child(4) div.sticky-bottom.well.bg-light.p-4.border div.btn-group button.btn.bg-info.bg-opacity-25.gotoTop:nth-child(1) > i.bi.bi-arrow-bar-up').click()
      cy.wait(1000)
      //cy.get('div.container:nth-child(2) main.my-4 div.row:nth-child(4) div.col-md-8 form.form-inline:nth-child(4) div.well > button.btn.btn-link.gotoTop').click()
      cy.wait(2000)
      //cy.get('div.container:nth-child(2) footer.d-flex.flex-wrap.justify-content-between.align-items-center.py-3.my-4.border-top div.col-md-4.d-flex.align-items-center span.text-muted > a:nth-child(1)').click()
      cy.wait(2000)

      })
    })
  })